### ISSUE TITLE
Update to 0.8.1

### ISSUE THREAD

**Issue by thefosk** [heroku/heroku-buildpack-kong#7]
Can we update the build-pack to the latest 0.8.x version?

**Comment by holgersindbaek** [comment]
+1

I don't wanna pay $75 a month for Cassandra on Heroku. Let's get things updates, so we can use Postgres!

Accidentally made a duplicate here btw: https://github.com/heroku/heroku-kong/issues/9.

@thefosk Any update on this? Is anyone looking into this?

**Comment by mars** [comment]
Our Kong 0.8 release is still in-progress for two reasons, both related to Heroku's enforcement of SSL connections with databases:

* [Those mysterious Cassandra errors](https://github.com/heroku/heroku-kong/issues/6) have finally been diagnosed: [SSL certificate handling in the cluster keepalive timer](https://github.com/openresty/lua-nginx-module/issues/709). The fix is in [ngx_http_lua_module 0.10.3](https://github.com/openresty/lua-nginx-module/commit/92c6b8d422ffdb73ace97b96efe3bffe4a1f39fc) which is not yet included in OpenResty (the app framework Kong is built on), as [the most recent release contains ngx_http_lua_module 0.10.2](http://openresty.org/en/changelog-1009007.html)
* Postgres support awaits [SSL support in pgmoon](https://github.com/leafo/pgmoon/pull/24)

We are considering forking these dependencies to get the fixes, but are cautious about further diverging Heroku Kong from Mashape's official distribution.

**Comment by holgersindbaek** [comment]
@mars Thanks for the update. It's much appreciated. 

If I want to get up and running with Kong and I don't want to pay those $75/m for a Cassandra server on Heroku, what do you suggest I do? Is there a service (Docker, AWS) that people tend to host Kong on more than other services?

**Comment by mars** [comment]
@holgersindbaek [Kong Installation](https://getkong.org/install/) is the best resource I know of to find other deployment solutions. I'm bummed our Postgres support is lagging, but can confidently say it will best the best deployment option once it's released 😝

**Comment by holgersindbaek** [comment]
@mars Haha... I believe that. I'm still very new to Kong, so trying to go with the most straight forward solution. Do you have any sense of a timeframe for Kong/Heroku/Postgres? I'm just playing around with Kong now, but won't really need a production server until 2-3 weeks from now.

**Comment by ericmwalsh** [comment]
@mars It looks like the PR is merged and going to be included in the 0.9.0 release, any chance at an update soon?

**Comment by mars** [comment]
@ericmwalsh Once 0.9 is released, I'll look into performing the upgrade. Hoping it will be pretty simple since all the blockers have been resolved.

**Comment by ericmwalsh** [comment]
Thanks, @mars! Let me know if you need any help, I've been using your buildpack for quite a while and figure I should give back to the project/community.

**Comment by mars** [comment]
We've looked at porting our [Kong patches](https://github.com/Mashape/kong/compare/master...mars:0.7.0-external-supervisor) up to 0.9.0, and the CLI codebase has totally changed. We're no longer planning to perform this upgrade, but we will leave the buildpack on-line for those who have existing deployments.

**Comment by andjosh** [comment]
@mars Is there a particular reason to avoid porting to `0.9.0`? I have an existing deployment and may be interested in starting a port (or a new package), but haven't taken a close look at the changelog. Is there anything you think may prevent Kong `0.9.0` from using a similar deployment structure?

**Comment by mars** [comment]
@andjosh see ["Foreground process model" issue](https://github.com/Mashape/kong/issues/928) for background. Once digested, checkout the [patch used for Kong 0.7 on Heroku](https://github.com/Mashape/kong/compare/master...mars:0.7.0-external-supervisor) to support a [supervised process model](https://github.com/heroku/heroku-kong/blob/master/Procfile.web) using the [runit buildpack](https://github.com/heroku/heroku-kong/blob/master/.buildpacks#L2).

Then, investigate how to apply similar patches for foreground/supervised processes in 0.9. We found that the Kong CLI change so dramatically between 0.7 & 0.9 that our patches no longer apply without significant engineering.

**Comment by capitalist** [comment]
Does this mean, then, there is no straightforward way to run the latest Kong on Heroku?

**Comment by mars** [comment]
Unfortunately, that is true @capitalist. We devoted a couple months (Jan-Feb 2016) of full-time engineering to make Kong 0.6 & 0.7 run on Heroku, plus more during the summer working toward 0.8. 

Between the lack of support we received to merge those patches into Kong (or otherwise implement the process supervision architecture) and then the rewrite of the Kong CLI (the code we patched) for version 0.9, we've run out of steam 💨

**Comment by capitalist** [comment]
Thanks @mars. That's certainly understandable.
